// app/layout.tsx (Server-side)
import { Metadata } from 'next';
import './ui/globals.css';  // Your global CSS
import ClientLayout from './admin/components/ClientLayout';
import { cn } from '@/lib/utils';
import { Inter } from 'next/font/google'; // Import the Inter font

// Define Google font (Inter)
const inter = Inter({
  subsets: ['latin'], // Specify the subset
  variable: "--font-inter",
  display: 'swap',
});


// Metadata to be applied in the HTML head
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en"  >
      <body suppressHydrationWarning className={cn(inter.className, {"debug-screens" : process.env.NODE_ENV === "development"})}>
        {/* Render the ClientLayout which includes the Redux Provider */}
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
